db:
  image: postgres:15
  user: postgres
  password: postgres
  userDB:
    name: userdb
    svcName: user-db
  driverDB:
    name: driverdb
    svcName: driver-db
  bookingDB:
    name: bookingdb
    svcName: booking-db
  paymentDB:
    name: paymentdb
    svcName: payment-db
  
secret:
  jwtKey: "pQaLtYxVnBrKmeZs"

app:
  user:
    name: "user-app"
    image: "user-service:latest"
  driver:
    name: "driver-app"
    image: "driver-service:latest"
  booking:
    name: "booking-app"
    image: "booking-service:latest"
  payment:
    name: "payment-app"
    image: "payment-service:latest"

resources:
  limits:
    cpu: "50m"
    memory: "256Mi"
  requests:
    cpu: "25m"
    memory: "128Mi"