db:
  image: postgres:15
  user: postgres
  password: postgres
  userDB:
    name: userdb
    svcName: user-db
  driverDB:
    name: driverdb
    svcName: driver-db
  bookingDB:
    name: bookingdb
    svcName: booking-db
  paymentDB:
    name: paymentdb
    svcName: payment-db
  
secret:
  jwtKey: "pQaLtYxVnBrKmeZs"

app:
  user:
    name: "user-app"
    image: "user-service:latest"
    host: "user.ss-cab-booking.local"
  driver:
    name: "driver-app"
    image: "driver-service:latest"
    host: "driver.ss-cab-booking.local"
  booking:
    name: "booking-app"
    image: "booking-service:latest"
    host: "booking.ss-cab-booking.local"
  payment:
    name: "payment-app"
    image: "payment-service:latest"
    host: "payment.ss-cab-booking.local"
  notification:
    name: "notification-app"
    image: "notification-service:latest"
    host: "notification.ss-cab-booking.local"

resources:
  limits:
    cpu: "50m"
    memory: "256Mi"
  requests:
    cpu: "25m"
    memory: "128Mi"

rabitMQ:
  queueName: "booking_queue"
  appName: "rabbitmq"